In [3]:
# Importa numpy
import numpy as np

In [4]:
# Crear array
array = np.array(
    [[1,  6, 11],
    [2,  7, 12],
    [3,  8, 13],
    [4,  9, 14],
    [5, 10, 15]]
)

In [5]:
# Averigua la forma del array (5 filas x 2 columnas)
array.shape

(5, 3)

In [13]:
# Selecciona la segunda columna del array (El array parte contando desde 0)
array[:, 1]

array([ 6,  7,  8,  9, 10])

In [10]:
# Crea un vector con los valores del 15 al 55, llamalo array2. Pista: usa np.arange
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [15]:
# Asigna el valor 23 a la quinta posicion del array2
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [19]:
# Convierte array2 del revés (es decir [55,54,....,15]
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [ ]:
# Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala matriz_diag
# pista: usa np.diag

In [31]:
      # Ver pares --> arr[par/impar::saltos]
      array2[1::2]

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48,
       50, 52, 54])

In [25]:
      #ver pares con 5 primeros
      array2[1::2][:5]

array([16, 18, 20, 22, 24])

In [33]:
matriz_diag = np.diag(array2[1::2][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [34]:
# Imprime el numero de dimensiones de matriz_diag
matriz_diag.ndim

2

In [35]:
# Crea una matriz con números aleatorios de tamaño 5x3 (4 filas por 3 columnas), llamala matriz
matriz = np.random.random((5,3))
matriz

array([[0.15662781, 0.63584206, 0.02790964],
       [0.82960343, 0.18974344, 0.64930255],
       [0.06564144, 0.01665107, 0.83138478],
       [0.77337658, 0.76483699, 0.76018388],
       [0.92135513, 0.68365887, 0.70391165]])

In [38]:
# Multiplica matriz por matriz_diag
matriz.T.shape
matriz.T @ matriz_diag

array([[ 2.50604489, 14.93286168,  1.31282874, 17.01428484, 22.11252302],
       [10.17347298,  3.41538187,  0.33302134, 16.82641382, 16.40781277],
       [ 0.44655419, 11.68744588, 16.62769558, 16.72404547, 16.89387955]])